

class DomSelectors:
    WEEK_SPAN_ELEMENT = "title"
    TREASURES_SECTION_ID = "section2"
    MINISTRY_SECTION_ID = "section3"
    CHRISTIAN_LIFE_SECTION_ID = "section4"
    MEETING_SECTION_TITLE_ELEMENT = "h2"
    PRESENTATIONS_GROUP_SELECTOR = "ul"
    PRESENTATION_ELEMENT = "li"
    PRESENTATION_TITLES_ELEMENT = "p"
